server:
  port: 9595
  servlet:
    context-path: /

spring:
  application:
    name: jstack-insight
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# SpringDoc / Swagger UI 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

logging:
  level:
    com.zeng.jstackinsight: DEBUG
